### PR TITLE
Fix cfi-icall breakage

### PR DESCRIPTION
**Pull request by lattera**
Signed-off-by:	Shawn Webb <shawn.webb@hardenedbsd.org>

### CODE REVIEW

**Comment by gwsw** [comment]
Thanks for the patch Shawn.  One question: I understand the change to add VOID_PARAM to the getccu prototype, but was there a reason you changed the four calls through the function pointers from the (*gr_getc)() style to gr_getc()?  AFAIK they are equivalent but the former is the style used elsewhere in less so I'd prefer to keep it consistent.

**Comment by lattera** [comment]
I can remove that. It was a stylistic thing that was bugging me while I was debugging the issue. Consider it leftover cruft.

Would you like me to update this PR to undo the stylistic changes? I'd be more than happy to do so.

**Comment by gwsw** [comment]
Yes, if you could trim it down to the necessary change, I'd appreciate it.

**Comment by lattera** [comment]
Done. :)

**Pull request merged**
