### PR TITLE
reduce less binary size by +2KB by use tabs in less.hlp

### PR DESCRIPTION
**Pull request by kloczek**
Reduce less binary size by use tabs in less.hlp.

$ size less.unexpand less.orig
   text    data     bss     dec     hex filename
 144496   20840   22376  187712   2dd40 less.unexpand
 146896   20840   22376  190112   2e6a0 less.orig

### CODE REVIEW

**Comment by avih** [comment]
One could argue that the help page should be formatted as intended, and unaffected by the terminal tab settings.

Personally I don't think this tradeoff is worth the 1% size saving...

**Comment by kloczek** [comment]
As this will merged I'm going to prepare another PR to use even more tab use to rearrange whole text to use lees spaces ano more tabs so total size reduction will be more than +two times bigger.

**Comment by gwsw** [comment]
The help file deliberately uses spaces rather than tabs, so that text is properly aligned regardless of the user's tab setting. The only way I can see this approach being feasible would be if the code changed the tab setting before viewing the help file and then restored it after exiting the help file. I don't think it's worth this complication to save a few kilobytes.

**Comment by kloczek** [comment]
Your choice ..

**Comment by avih** [comment]
> The only way I can see this approach being feasible would be if the code changed the tab setting before viewing the help file and then restored it after exiting the help file

Well, it's also possible that the content is tabs-to-spaces converted with a tab-equals-8 config, which should be trivial to do for ASCII content (I'm estimating at most 5 lines of code), and fairly simple with existing `wcwidth`-like code otherwise, as I presume `less` already has ways to calculate on-screen width of strings - which is required for tabs-to-spaces conversion.

**Comment by kloczek** [comment]
Q: did anyone tested that using tabs trashes output on DOS/Win? 🤔

**Pull request closed without merging**
